spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  
    
server:
  port: 8765
 
jwt:
  secret: oxktUVeFYg2KMcOpCmH+xqgPkbcQYBlaGGOI75hZrss
  
    