name: Integracao continua com github actions

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy pessoa
        run: |
          docker pull rodrigodocker158/pessoa:${{ vars.DOCKER_IMAGE_VERSION_PROD }}
          docker rm -f pessoa || true
          docker run -d -p 8790:8700 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://pessoa-db:5432/pessoa \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
            --name pessoa \
            rodrigodocker158/pessoa:${{ vars.DOCKER_IMAGE_VERSION_PROD }}

      - name: Deploy multa
        run: |
          docker pull rodrigodocker158/multa:${{ vars.DOCKER_IMAGE_VERSION_PROD }}
          docker rm -f multa || true
          docker run -d -p 9080:9000 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://multa-db:5432/multa \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
            --name multa \
            rodrigodocker158/multa:${{ vars.DOCKER_IMAGE_VERSION_PROD }}

      - name: Deploy cliente
        run: |
          docker pull rodrigodocker158/clientes.springboot:${{ vars.DOCKER_IMAGE_VERSION_PROD }}
          docker rm -f cliente || true
          docker run -d -p 8300:8200 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://cliente-db:5432/usuarios_microservicos \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
            -e SECURITY_JWT_TOKEN_SECRET_KEY=${{ secrets.JWT_SECRET }} \
            --name cliente \
            rodrigodocker158/clientes.springboot:${{ vars.DOCKER_IMAGE_VERSION_PROD }}

      - name: Deploy book
        run: |
          docker pull rodrigodocker158/book:${{ vars.DOCKER_IMAGE_VERSION_PROD }}
          docker rm -f book || true
          docker run -d -p 8070:8000 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://livro-db:5432/livro \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
            --name book \
            rodrigodocker158/book:${{ vars.DOCKER_IMAGE_VERSION_PROD }}

      - name: Deploy aluguel
        run: |
          docker pull rodrigodocker158/aluguel:${{ vars.DOCKER_IMAGE_VERSION_PROD }}
          docker rm -f aluguel || true
          docker run -d -p 8170:8100 \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://aluguel-db:5432/aluguel \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka \
            --name aluguel \
            rodrigodocker158/aluguel:${{ vars.DOCKER_IMAGE_VERSION_PROD }}
