name: Integracao continua com github actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: login no docker hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build containers
        run: |
          cd naming-server && mvn spring-boot:build-image -DskipTests
          cd ../api-gateway && mvn spring-boot:build-image -DskipTests
          cd ../pessoa && mvn clean package -DskipTests
          cd ../book && mvn clean package -DskipTests
          cd ../cliente_microservicos && mvn clean package -DskipTests
          cd ../aluguel && mvn clean package -DskipTests
          cd ../multa && mvn clean package -DskipTests

      - name: Build Docker images
        run: docker compose build

      - name: Push to Docker Hub
        run: |
          docker tag rodrigodocker158/naming-server:latest rodrigodocker158/naming-server:${{ github.sha }}
          docker tag rodrigodocker158/api-gateway:latest rodrigodocker158/api-gateway:${{ github.sha }}
          docker tag rodrigodocker158/pessoa:latest rodrigodocker158/pessoa:${{ github.sha }}
          docker tag rodrigodocker158/book:latest rodrigodocker158/book:${{ github.sha }}
          docker tag rodrigodocker158/multa:latest rodrigodocker158/multa:${{ github.sha }}
          docker tag rodrigodocker158/clientes.springboot:latest rodrigodocker158/clientes.springboot:${{ github.sha }}
          docker tag rodrigodocker158/aluguel:latest rodrigodocker158/aluguel:${{ github.sha }}

          docker push rodrigodocker158/naming-server:${{ github.sha }}
          docker push rodrigodocker158/api-gateway:${{ github.sha }}
          docker push rodrigodocker158/pessoa:${{ github.sha }}
          docker push rodrigodocker158/book:${{ github.sha }}
          docker push rodrigodocker158/multa:${{ github.sha }}
          docker push rodrigodocker158/clientes.springboot:${{ github.sha }}
          docker push rodrigodocker158/aluguel:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy with Docker Compose
        run: |
          docker compose pull
          docker compose up -d
